### ISSUE TITLE
This has been of great help - open to pull requests?

### ISSUE THREAD

**Issue by tikimcfee** [Manuiq/ZoomableTextureView#2]
Hello hello!

First, just gotta say this is a great utility class. I have very little experience with matrix manipulation and transformation on Android, and your use case spells out a lot of the details that I'm still reading over (ha!)

I noticed that you had a `{TODO: fix ugly code;}` in there, and I was wondering if I could be of any help. I have a slightly different use case of a zooming texture view, but I think we share a lot of the fundamentals. I'll (sadly) leave up to you the aspect ratio issue, but I _can_ offer a little bit of abstraction / cleaning help if you're interested. I'm not master architect (far from it), but I reorganized things while reading through to get a clearer picture of what was happening between the `ZoomOnTouchListeners` and the `TextureView` itself. A couple interfaces, little bit of separation, variable naming, that kinda thing.

If you're interested in perhaps rejiggering your structure around a bit, I would love to share and get some feedback on the changes I've made. Just let me know!

**Comment by Manuiq** [comment]
Hi, that would be really helpful. I would definetely love to see someone's else take on this. Go ahead, just create a pull request with your code vision and I'll merge it.
