### ISSUE TITLE
Hide The Controls in Exoplayer.!!!

### ISSUE THREAD

**Issue by sahilcsgroup** [Manuiq/ZoomableTextureView#3]
When i try to implement this with Exoplayer, it didn't show the Play/Pause, seekbar like controls.. 
Can anyone help me out with this.

**Comment by Manuiq** [comment]
Hi. You were probably looking at sample code for SimpleExoPlayer which does not have controls in the first place. You were probable mistaking it with SimpleExoPlayer**View** which indeed provides them out of the box. Anyways, I've added a sample to repository to show how you can do it. It's a bit tricky cause SimpleExoPlayerView creates its surface internally so I had to create a custom ZoomableExoPlayerView(which differs only in what TextureView it creates).

 Also a new problem arises where now you not only have to intercept touch event to zoom on video, but also dedicate some gestures to show/hide controls after timeout (so at the moment controls are just showed all the time).
